# Generated by Django 5.1.1 on 2024-10-31 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_lyrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
